# Rotten Tomato 데이터셋 전처리

- Date: 21.08.26
- Made by Cheonsol Lee

In [110]:
import pandas as pd
import os
import datetime
os.getcwd()

'C:\\Users\\user\\Jupyter_project\\keejun\\NLP_GNN_STUDY\\Movie'

In [63]:
path = './../../data/rotten_tomato/'
os.listdir(path)

['model.pth',
 'model_rotten.pth',
 'movie1_neg.txt',
 'movie1_pos.txt',
 'movie2_neg.txt',
 'movie2_pos.txt',
 'movie3_neg.txt',
 'movie3_pos.txt',
 'rotten_review_scaled.csv',
 'rotten_review_scaled_clean.csv',
 'rotten_review_scaled_label.csv',
 'rotten_tomatoes_critic_reviews.csv',
 'rotten_tomatoes_movies.csv']

### 1. Load the data

In [64]:
rotten_review = pd.read_csv(os.path.join(path + 'rotten_tomatoes_critic_reviews.csv'), encoding='utf-8')
print(rotten_review.shape)

(1130017, 8)

In [65]:
rotten_movie = pd.read_csv(os.path.join(path + 'rotten_tomatoes_movies.csv'), encoding='utf-8')
print(rotten_movie.shape)

(17712, 22)

In [66]:
rotten_review.head()

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,m/0814255,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...
1,m/0814255,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff..."
2,m/0814255,NaN,False,FILMINK (Australia),Fresh,NaN,2010-02-09,With a top-notch cast and dazzling special eff...
3,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...
4,m/0814255,Ethan Alter,True,Hollywood Reporter,Rotten,NaN,2010-02-10,What's really lacking in The Lightning Thief i...

In [67]:
set(rotten_review.review_score)

{'0',
 '0.02/5',
 '0.05/4',
 '0.1/5',
 '0.13/1',
 '0.13/5',
 '0.2/5',
 '0.21/10',
 '0.25/4',
 '0.3/5',
 '0.4/5',
 '0.5/10',
 '0.5/4',
 '0.5/5',
 '0.5/5.5',
 '0.52/1',
 '0.58/1',
 '0.59/1',
 '0.6/1',
 '0.6/10',
 '0.65/10',
 '0.66/10',
 '0.664363/10',
 '0.666/4',
 '0.7221/10',
 '0.75/10',
 '0.75/5',
 '0.7765823/10',
 '0.8/10',
 '0.8/5',
 '0.81/1',
 '0.82/10',
 '0.85/10',
 '0.9/10',
 '0.96/10',
 '0/10',
 '0/100',
 '0/1000',
 '0/4',
 '0/5',
 '0/6',
 '1',
 '1.1/10',
 '1.1/2',
 '1.1/5',
 '1.2/10',
 '1.2/4',
 '1.2/5',
 '1.21/10',
 '1.24/5',
 '1.25/4',
 '1.25/5',
 '1.3/5',
 '1.35/5',
 '1.4/10',
 '1.4/4',
 '1.4/5',
 '1.5/10',
 '1.5/2',
 '1.5/3',
 '1.5/4',
 '1.5/5',
 '1.5/6',
 '1.5242228/10',
 '1.6/5',
 '1.62/5',
 '1.7/5',
 '1.75/10',
 '1.75/4',
 '1.75/5',
 '1.8/10',
 '1.8/4',
 '1.8/5',
 '1.82/10',
 '1.85/10',
 '1.88/10',
 '1.9/10',
 '1.9/5',
 '1.9528/10',
 '1/1',
 '1/10',
 '1/2',
 '1/3',
 '1/4',
 '1/5',
 '1/54',
 '1/6',
 '10',
 '10.50/20',
 '10/10',
 '10/100',
 '10/20',
 '10/90',
 '100/100',
 '11.5/20',
 '11/100',
 '11/20',
 '12.5/20',
 '12.50/20',
 '12/100',
 '12/20',
 '13.5/20',
 '13/100',
 '13/20',
 '14',
 '14.5/20',
 '14.50/20',
 '14/100',
 '14/20',
 '15.5/20',
 '15/100',
 '15/20',
 '16.5/20',
 '16/100',
 '16/20',
 '17.5/20',
 '17/20',
 '18.5/20',
 '18/100',
 '18/20',
 '19/100',
 '19/20',
 '2',
 '2.1/10',
 '2.1/2',
 '2.1/5',
 '2.11/5',
 '2.12/5',
 '2.2/10',
 '2.2/5',
 '2.20282652/10',
 '2.212521/10',
 '2.25/4',
 '2.25/5',
 '2.255/5',
 '2.282303/10',
 '2.3/10',
 '2.3/4',
 '2.3/5',
 '2.4/10',
 '2.4/4',
 '2.4/5',
 '2.5/10',
 '2.5/20',
 '2.5/3',
 '2.5/4',
 '2.5/5',
 '2.5/50',
 '2.5/6',
 '2.50/5',
 '2.55/4',
 '2.55/5',
 '2.6/10',
 '2.6/4',
 '2.6/5',
 '2.6/6',
 '2.65/10',
 '2.7/10',
 '2.7/4',
 '2.7/5',
 '2.74/10',
 '2.75/10',
 '2.75/3',
 '2.75/4',
 '2.75/5',
 '2.8/10',
 '2.8/4',
 '2.8/5',
 '2.83/5',
 '2.85/5',
 '2.89/5',
 '2.892521821/10',
 '2.9/10',
 '2.9/5',
 '2.95/10',
 '2.95/5',
 '2/10',
 '2/100',
 '2/2',
 '2/20',
 '2/3',
 '2/4',
 '2/5',
 '2/54',
 '2/6',
 '2/8',
 '2/9',
 '20/100',
 '20/20',
 '21/100',
 '21/24',
 '22/100',
 '23/100',
 '24',
 '24/100',
 '25',
 '25/100',
 '25/4',
 '26/100',
 '27/100',
 '28/100',
 '29/100',
 '3',
 '3.021/10',
 '3.0782/10',
 '3.1/10',
 '3.1/5',
 '3.15/5',
 '3.2/10',
 '3.2/4',
 '3.2/5',
 '3.20/10',
 '3.2121/10',
 '3.222423/10',
 '3.25/10',
 '3.25/4',
 '3.25/5',
 '3.3/10',
 '3.3/4',
 '3.3/5',
 '3.35/5',
 '3.4/10',
 '3.4/4',
 '3.4/5',
 '3.45/5',
 '3.5/10',
 '3.5/18',
 '3.5/20',
 '3.5/3',
 '3.5/4',
 '3.5/44',
 '3.5/5',
 '3.5/5.5',
 '3.5/6',
 '3.515/10',
 '3.54/5',
 '3.55/10',
 '3.56339/10',
 '3.6/10',
 '3.6/4',
 '3.6/5',
 '3.65/10',
 '3.65/5',
 '3.7/10',
 '3.7/5',
 '3.75/10',
 '3.75/4',
 '3.75/5',
 '3.7521/10',
 '3.76/10',
 '3.76/5',
 '3.7822391/10',
 '3.8/10',
 '3.8/5',
 '3.83412437/10',
 '3.85/10',
 '3.9/10',
 '3.9/5',
 '3.99/10',
 '3/10',
 '3/100',
 '3/20',
 '3/3',
 '3/4',
 '3/40',
 '3/45',
 '3/5',
 '3/5.4',
 '3/5.5',
 '3/6',
 '30/100',
 '31/100',
 '32/100',
 '33/100',
 '34',
 '34/100',
 '35',
 '35/100',
 '35/4',
 '36/100',
 '37/100',
 '38/100',
 '39/100',
 '39/40',
 '4',
 '4.0001/10',
 '4.021/10',
 '4.05524/10',
 '4.1/10',
 '4.1/5',
 '4.143641/10',
 '4.2/10',
 '4.2/5',
 '4.21/10',
 '4.211/10',
 '4.2112/10',
 '4.21382343/10',
 '4.22/10',
 '4.25/10',
 '4.25/5',
 '4.293382/10',
 '4.3/10',
 '4.3/5',
 '4.35/10',
 '4.35/5',
 '4.364221/10',
 '4.4/10',
 '4.4/5',
 '4.42/10',
 '4.45/10',
 '4.5/10',
 '4.5/4',
 '4.5/5',
 '4.5/6',
 '4.51/10',
 '4.521/10',
 '4.55/10',
 '4.558/10',
 '4.56/10',
 '4.6/10',
 '4.6/5',
 '4.65/10',
 '4.65/5',
 '4.7/10',
 '4.7/5',
 '4.70/10',
 '4.75/10',
 '4.75/5',
 '4.79/10',
 '4.8/10',
 '4.8/5',
 '4.827/10',
 '4.85/10',
 '4.86/10',
 '4.89/10',
 '4.89215/10',
 '4.9/10',
 '4.90/10',
 '4.95/10',
 '4.95/5',
 '4.9834326/10',
 '4.9837/10',
 '4/0',
 '4/10',
 '4/100',
 '4/3.5',
 '4/4',
 '4/5',
 '4/5.5',
 '4/6',
 '4/8',
 '40/100',
 '41/100',
 '42/100',
 '43/100',
 '44/100',
 '45',
 '45/100',
 '45/5',
 '46',
 '46/100',
 '47/100',
 '47/50',
 '48',
 '48/100',
 '49/100',
 '5',
 '5.01/10',
 '5.02120621/10',
 '5.046/10',
 '5.05/10',
 '5.1/10',
 '5.10/10',
 '5.12/10',
 '5.1221/10',
 '5.15/10',
 '5.1921/10',
 '5.2/10',
 '5.21/10',
 '5.212/10',
 '5.22/10',
 '5.23/10',
 '5.232121/10',
 '5.25/10',
 '5.284849/10',
 '5.3/10',
 '5.35/10',
 '5.4/10',
 '5.4221/10',
 '5.44/10',
 '5.45/10',
 '5.48/10',
 '5.49/10',
 '5.5/10',
 '5.5/20',
 '5.5/5',
 '5.5/6',
 '5.50/10',
 '5.51/10',
 '5.55/10',
 '5.5542/10',
 '5.56/10',
 '5.57/10',
 '5.6/10',
 '5.61/10',
 '5.623433899/10',
 '5.65/10',
 '5.6521/10',
 '5.6642/10',
 '5.67/10',
 '5.7/10',
 '5.70/10',
 '5.72/10',
 '5.75/10',
 '5.751/10',
 '5.76/10',
 '5.78/10',
 '5.8/10',
 '5.80/10',
 '5.81/10',
 '5.82/10',
 '5.8311/10',
 '5.85/10',
 '5.872/10',
 '5.88/10',
 '5.8921/10',
 '5.8943/10',
 '5.895/10',
 '5.89521/10',
 '5.9/10',
 '5.95/10',
 '5.9737991/10',
 '5.9821/10',
 '5.9999/10',
 '5/10',
 '5/100',
 '5/11',
 '5/20',
 '5/5',
 '5/6',
 '5/8',
 '50/100',
 '51/100',
 '52/100',
 '53/100',
 '54/100',
 '55/100',
 '56/100',
 '57/100',
 '58/100',
 '59/100',
 '59/60',
 '6',
 '6.0000001/10',
 '6.000003231/10',
 '6.00001/10',
 '6.0001/10',
 '6.00024/10',
 '6.001/10',
 '6.01/10',
 '6.02/10',
 '6.02121/10',
 '6.05/10',
 '6.09/10',
 '6.1/10',
 '6.1121/10',
 '6.15/10',
 '6.16/10',
 '6.19/10',
 '6.2/10',
 '6.24/10',
 '6.25/10',
 '6.26/10',
 '6.3/10',
 '6.35/10',
 '6.4/10',
 '6.45/10',
 '6.4821/10',
 '6.5/10',
 '6.55/10',
 '6.6/10',
 '6.65/10',
 '6.68/10',
 '6.7/10',
 '6.7/8',
 '6.75/10',
 '6.765/10',
 '6.78/10',
 '6.8/10',
 '6.84/10',
 '6.85/10',
 '6.8666/10',
 '6.875/10',
 '6.8843/10',
 '6.89/10',
 '6.9/10',
 '6.95/10',
 '6.96/10',
 '6.9621/10',
 '6.97/10',
 '6.98/10',
 '6.9921/10',
 '6/10',
 '6/11',
 '6/13',
 '6/20',
 '6/5',
 '6/6',
 '6/8',
 '60/100',
 '61/00',
 '61/100',
 '62/100',
 '63/100',
 '64/100',
 '65/100',
 '66/100',
 '66/70',
 '67',
 '67/10',
 '67/100',
 '68',
 '68/100',
 '69/100',
 '69/70',
 '7',
 '7.001/10',
 '7.00122/10',
 '7.01/10',
 '7.0155/10',
 '7.02/10',
 '7.021/10',
 '7.04/10',
 '7.05/10',
 '7.0921/10',
 '7.1/10',
 '7.10/10',
 '7.111113314/10',
 '7.12/10',
 '7.15/10',
 '7.18321/10',
 '7.2/10',
 '7.21/10',
 '7.212121/10',
 '7.218/10',
 '7.22/10',
 '7.2234238/10',
 '7.25/10',
 '7.2521/10',
 '7.2621/10',
 '7.3/10',
 '7.35/10',
 '7.3821/10',
 '7.3856/10',
 '7.4/10',
 '7.42/10',
 '7.44/10',
 '7.45/10',
 '7.48/10',
 '7.49/10',
 '7.4921/10',
 '7.5/10',
 '7.5/20',
 '7.5211/10',
 '7.5314585/10',
 '7.55/10',
 '7.57/10',
 '7.6/10',
 '7.61/10',
 '7.621/10',
 '7.62121/10',
 '7.65/10',
 '7.696/10',
 '7.7/10',
 '7.75/10',
 '7.79/10',
 '7.8/10',
 '7.825/10',
 '7.83/10',
 '7.85/10',
 '7.87/10',
 '7.89/10',
 '7.892/10',
 '7.9/10',
 '7.94/10',
 '7.94215/10',
 '7.95/10',
 '7.96/10',
 '7.98/10',
 '7/10',
 '7/11',
 '7/20',
 '7/5',
 '7/8',
 '70',
 '70/100',
 '71/100',
 '72',
 '72/100',
 '73/10',
 '73/100',
 '74/100',
 '75',
 '75/10',
 '75/100',
 '76/10',
 '76/100',
 '77',
 '77/100',
 '78/100',
 '79/100',
 '79/80',
 '8',
 '8.01/10',
 '8.05/10',
 '8.1/10',
 '8.10/10',
 '8.124/10',
 '8.15/10',
 '8.16/10',
 '8.19/10',
 '8.1921/10',
 '8.199/10',
 '8.2/10',
 '8.21/10',
 '8.212121/10',
 '8.225/10',
 '8.24/10',
 '8.25/10',
 '8.251/10',
 '8.2521/10',
 '8.26/10',
 '8.2621/10',
 '8.3/10',
 '8.3/100',
 '8.30/10',
 '8.32/10',
 '8.32321/10',
 '8.327/10',
 '8.35/10',
 '8.3721/10',
 '8.385/10',
 '8.39421/10',
 '8.4/10',
 '8.42/10',
 '8.425/10',
 '8.45/10',
 '8.453895/10',
 '8.458/10',
 '8.485/10',
 '8.496/10',
 '8.5/10',
 '8.5/5',
 '8.50/10',
 '8.53899/10',
 '8.55/10',
 '8.56/10',
 '8.57/10',
 '8.5788222/10',
 '8.6/10',
 '8.61/10',
 '8.621/10',
 '8.65/10',
 '8.666/10',
 '8.67/10',
 '8.68/10',
 '8.692121/10',
 '8.7/10',
 '8.70/10',
 '8.71/10',
 '8.72/10',
 '8.7328/10',
 '8.735/10',
 '8.74/10',
 '8.75/10',
 '8.76/10',
 '8.765/10',
 '8.8/10',
 '8.84/10',
 '8.85/10',
 '8.87/10',
 '8.88/10',
 '8.881/10',
 '8.89/10',
 '8.899327/10',
 '8.9/10',
 '8.901/10',
 '8.92/10',
 '8.921/10',
 '8.95/10',
 '8.9521/10',
 '8.9621/10',
 '8.98/10',
 '8.99/10',
 '8.999/10',
 '8/10',
 '8/100',
 '8/20',
 '8/5',
 '80',
 '80/100',
 '81/100',
 '82/100',
 '83/100',
 '84/100',
 '85/100',
 '86/100',
 '87/10',
 '87/100',
 '88',
 '88/100',
 '89',
 '89/100',
 '9',
 '9.01/10',
 '9.021/10',
 '9.1/10',
 '9.12/10',
 '9.121/10',
 '9.1221/10',
 '9.14/10',
 '9.1421/10',
 '9.145/10',
 '9.15/10',
 '9.16/10',
 '9.18/10',
 '9.188/10',
 '9.19/10',
 '9.2/10',
 '9.20/10',
 '9.2021/10',
 '9.21/10',
 '9.25/10',
 '9.26/10',
 '9.3/10',
 '9.30/10',
 '9.33/10',
 '9.35/10',
 '9.38/10',
 '9.4/10',
 '9.45/10',
 '9.46/10',
 '9.48/10',
 '9.49/10',
 '9.5/10',
 '9.5/20',
 '9.5/5',
 '9.50/20',
 '9.51/10',
 '9.52/10',
 '9.552/10',
 '9.56/10',
 '9.6/10',
 '9.6421/10',
 '9.649821/10',
 '9.65/10',
 '9.66/10',
 '9.67/10',
 '9.68/10',
 '9.7/10',
 '9.73889/10',
 '9.74/10',
 '9.75/10',
 '9.76/10',
 '9.78/10',
 '9.79/10',
 '9.8/10',
 '9.85/10',
 '9.851/10',
 '9.8521/10',
 '9.85621/10',
 '9.86/10',
 '9.865/10',
 '9.87/10',
 '9.88/10',
 '9.889/10',
 '9.89/10',
 '9.9/10',
 '9.921/10',
 '9.95/10',
 '9.99/10',
 '9/10',
 '9/100',
 '9/20',
 '9/5',
 '90',
 '90/100',
 '91/100',
 '910',
 '92/100',
 '920',
 '93/100',
 '94/100',
 '95',
 '95/100',
 '95/95',
 '96/100',
 '97/100',
 '98/100',
 '99/100',
 'A',
 'A  -',
 'A-',
 'B',
 'B+',
 'B-',
 'C',
 'C  -',
 'C+',
 'C-',
 'D',
 'D+',
 'D-',
 'F',
 nan}

In [68]:
rotten_review.dropna(axis=0, inplace=True)

In [69]:
len(rotten_review)

752734

In [70]:
rotten_review.head()

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
3,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...
6,m/0814255,Nick Schager,False,Slant Magazine,Rotten,1/4,2010-02-10,Harry Potter knockoffs don't come more transpa...
7,m/0814255,Bill Goodykoontz,True,Arizona Republic,Fresh,3.5/5,2010-02-10,"Percy Jackson isn't a great movie, but it's a ..."
8,m/0814255,Jordan Hoffman,False,UGO,Fresh,B,2010-02-10,"Fun, brisk and imaginative"
9,m/0814255,Jim Schembri,True,The Age (Australia),Fresh,3/5,2010-02-10,"Crammed with dragons, set-destroying fights an..."

In [71]:
rotten_review['review_score'] = rotten_review['review_score'].str.replace(' ', '')

In [72]:
# 분수 형태의 review_score
set(rotten_review.review_score)

{'0',
 '0.02/5',
 '0.05/4',
 '0.1/5',
 '0.13/1',
 '0.13/5',
 '0.2/5',
 '0.21/10',
 '0.25/4',
 '0.3/5',
 '0.4/5',
 '0.5/10',
 '0.5/4',
 '0.5/5',
 '0.5/5.5',
 '0.52/1',
 '0.58/1',
 '0.59/1',
 '0.6/1',
 '0.6/10',
 '0.65/10',
 '0.66/10',
 '0.664363/10',
 '0.666/4',
 '0.7221/10',
 '0.75/10',
 '0.75/5',
 '0.7765823/10',
 '0.8/10',
 '0.8/5',
 '0.81/1',
 '0.82/10',
 '0.85/10',
 '0.9/10',
 '0.96/10',
 '0/10',
 '0/100',
 '0/1000',
 '0/4',
 '0/5',
 '0/6',
 '1',
 '1.1/10',
 '1.1/2',
 '1.1/5',
 '1.2/10',
 '1.2/4',
 '1.2/5',
 '1.21/10',
 '1.24/5',
 '1.25/4',
 '1.25/5',
 '1.3/5',
 '1.35/5',
 '1.4/10',
 '1.4/4',
 '1.4/5',
 '1.5/10',
 '1.5/2',
 '1.5/3',
 '1.5/4',
 '1.5/5',
 '1.5/6',
 '1.5242228/10',
 '1.6/5',
 '1.62/5',
 '1.7/5',
 '1.75/10',
 '1.75/4',
 '1.75/5',
 '1.8/10',
 '1.8/4',
 '1.8/5',
 '1.82/10',
 '1.85/10',
 '1.88/10',
 '1.9/10',
 '1.9/5',
 '1.9528/10',
 '1/1',
 '1/10',
 '1/2',
 '1/3',
 '1/4',
 '1/5',
 '1/54',
 '1/6',
 '10',
 '10.50/20',
 '10/10',
 '10/100',
 '10/20',
 '10/90',
 '100/100',
 '11.5/20',
 '11/20',
 '12.5/20',
 '12.50/20',
 '12/100',
 '12/20',
 '13.5/20',
 '13/100',
 '13/20',
 '14',
 '14.5/20',
 '14.50/20',
 '14/100',
 '14/20',
 '15.5/20',
 '15/100',
 '15/20',
 '16.5/20',
 '16/100',
 '16/20',
 '17.5/20',
 '17/20',
 '18.5/20',
 '18/100',
 '18/20',
 '19/100',
 '19/20',
 '2',
 '2.1/10',
 '2.1/2',
 '2.1/5',
 '2.11/5',
 '2.12/5',
 '2.2/10',
 '2.2/5',
 '2.20282652/10',
 '2.212521/10',
 '2.25/4',
 '2.25/5',
 '2.255/5',
 '2.282303/10',
 '2.3/10',
 '2.3/4',
 '2.3/5',
 '2.4/10',
 '2.4/4',
 '2.4/5',
 '2.5/10',
 '2.5/20',
 '2.5/3',
 '2.5/4',
 '2.5/5',
 '2.5/50',
 '2.5/6',
 '2.50/5',
 '2.55/4',
 '2.55/5',
 '2.6/10',
 '2.6/4',
 '2.6/5',
 '2.6/6',
 '2.65/10',
 '2.7/10',
 '2.7/4',
 '2.7/5',
 '2.74/10',
 '2.75/10',
 '2.75/3',
 '2.75/4',
 '2.75/5',
 '2.8/10',
 '2.8/4',
 '2.8/5',
 '2.83/5',
 '2.85/5',
 '2.89/5',
 '2.892521821/10',
 '2.9/10',
 '2.9/5',
 '2.95/10',
 '2.95/5',
 '2/10',
 '2/100',
 '2/2',
 '2/20',
 '2/3',
 '2/4',
 '2/5',
 '2/54',
 '2/6',
 '2/8',
 '2/9',
 '20/100',
 '20/20',
 '21/100',
 '21/24',
 '22/100',
 '23/100',
 '24',
 '24/100',
 '25',
 '25/100',
 '25/4',
 '26/100',
 '27/100',
 '28/100',
 '29/100',
 '3',
 '3.021/10',
 '3.0782/10',
 '3.1/10',
 '3.1/5',
 '3.15/5',
 '3.2/10',
 '3.2/4',
 '3.2/5',
 '3.20/10',
 '3.2121/10',
 '3.222423/10',
 '3.25/10',
 '3.25/4',
 '3.25/5',
 '3.3/10',
 '3.3/4',
 '3.3/5',
 '3.35/5',
 '3.4/10',
 '3.4/4',
 '3.4/5',
 '3.45/5',
 '3.5/10',
 '3.5/18',
 '3.5/20',
 '3.5/3',
 '3.5/4',
 '3.5/44',
 '3.5/5',
 '3.5/5.5',
 '3.5/6',
 '3.515/10',
 '3.54/5',
 '3.55/10',
 '3.56339/10',
 '3.6/10',
 '3.6/4',
 '3.6/5',
 '3.65/10',
 '3.65/5',
 '3.7/10',
 '3.7/5',
 '3.75/10',
 '3.75/4',
 '3.75/5',
 '3.7521/10',
 '3.76/10',
 '3.76/5',
 '3.7822391/10',
 '3.8/10',
 '3.8/5',
 '3.83412437/10',
 '3.85/10',
 '3.9/10',
 '3.9/5',
 '3.99/10',
 '3/10',
 '3/100',
 '3/20',
 '3/3',
 '3/4',
 '3/40',
 '3/45',
 '3/5',
 '3/5.4',
 '3/5.5',
 '3/6',
 '30/100',
 '31/100',
 '32/100',
 '33/100',
 '34',
 '34/100',
 '35',
 '35/100',
 '35/4',
 '36/100',
 '37/100',
 '38/100',
 '39/100',
 '39/40',
 '4',
 '4.0001/10',
 '4.021/10',
 '4.05524/10',
 '4.1/10',
 '4.1/5',
 '4.143641/10',
 '4.2/10',
 '4.2/5',
 '4.21/10',
 '4.211/10',
 '4.2112/10',
 '4.21382343/10',
 '4.22/10',
 '4.25/10',
 '4.25/5',
 '4.293382/10',
 '4.3/10',
 '4.3/5',
 '4.35/10',
 '4.35/5',
 '4.364221/10',
 '4.4/10',
 '4.4/5',
 '4.42/10',
 '4.45/10',
 '4.5/10',
 '4.5/4',
 '4.5/5',
 '4.5/6',
 '4.51/10',
 '4.521/10',
 '4.55/10',
 '4.558/10',
 '4.56/10',
 '4.6/10',
 '4.6/5',
 '4.65/10',
 '4.65/5',
 '4.7/10',
 '4.7/5',
 '4.70/10',
 '4.75/10',
 '4.75/5',
 '4.79/10',
 '4.8/10',
 '4.8/5',
 '4.827/10',
 '4.85/10',
 '4.86/10',
 '4.89/10',
 '4.89215/10',
 '4.9/10',
 '4.90/10',
 '4.95/10',
 '4.95/5',
 '4.9834326/10',
 '4.9837/10',
 '4/0',
 '4/10',
 '4/100',
 '4/3.5',
 '4/4',
 '4/5',
 '4/5.5',
 '4/6',
 '4/8',
 '40/100',
 '41/100',
 '42/100',
 '43/100',
 '44/100',
 '45',
 '45/100',
 '45/5',
 '46',
 '46/100',
 '47/100',
 '47/50',
 '48',
 '48/100',
 '49/100',
 '5',
 '5.01/10',
 '5.02120621/10',
 '5.046/10',
 '5.05/10',
 '5.1/10',
 '5.10/10',
 '5.12/10',
 '5.1221/10',
 '5.15/10',
 '5.1921/10',
 '5.2/10',
 '5.21/10',
 '5.212/10',
 '5.22/10',
 '5.23/10',
 '5.232121/10',
 '5.25/10',
 '5.284849/10',
 '5.3/10',
 '5.35/10',
 '5.4/10',
 '5.4221/10',
 '5.44/10',
 '5.45/10',
 '5.48/10',
 '5.49/10',
 '5.5/10',
 '5.5/20',
 '5.5/5',
 '5.50/10',
 '5.51/10',
 '5.55/10',
 '5.5542/10',
 '5.56/10',
 '5.57/10',
 '5.6/10',
 '5.61/10',
 '5.623433899/10',
 '5.65/10',
 '5.6521/10',
 '5.6642/10',
 '5.67/10',
 '5.7/10',
 '5.70/10',
 '5.72/10',
 '5.75/10',
 '5.751/10',
 '5.76/10',
 '5.78/10',
 '5.8/10',
 '5.80/10',
 '5.81/10',
 '5.82/10',
 '5.8311/10',
 '5.85/10',
 '5.872/10',
 '5.88/10',
 '5.8921/10',
 '5.8943/10',
 '5.895/10',
 '5.89521/10',
 '5.9/10',
 '5.95/10',
 '5.9737991/10',
 '5.9821/10',
 '5.9999/10',
 '5/10',
 '5/100',
 '5/11',
 '5/20',
 '5/5',
 '5/6',
 '5/8',
 '50/100',
 '51/100',
 '52/100',
 '53/100',
 '54/100',
 '55/100',
 '56/100',
 '57/100',
 '58/100',
 '59/100',
 '59/60',
 '6',
 '6.0000001/10',
 '6.000003231/10',
 '6.00001/10',
 '6.0001/10',
 '6.00024/10',
 '6.001/10',
 '6.01/10',
 '6.02/10',
 '6.02121/10',
 '6.05/10',
 '6.09/10',
 '6.1/10',
 '6.1121/10',
 '6.15/10',
 '6.16/10',
 '6.19/10',
 '6.2/10',
 '6.24/10',
 '6.25/10',
 '6.26/10',
 '6.3/10',
 '6.35/10',
 '6.4/10',
 '6.45/10',
 '6.4821/10',
 '6.5/10',
 '6.55/10',
 '6.6/10',
 '6.65/10',
 '6.68/10',
 '6.7/10',
 '6.7/8',
 '6.75/10',
 '6.765/10',
 '6.78/10',
 '6.8/10',
 '6.84/10',
 '6.85/10',
 '6.8666/10',
 '6.875/10',
 '6.8843/10',
 '6.89/10',
 '6.9/10',
 '6.95/10',
 '6.96/10',
 '6.9621/10',
 '6.97/10',
 '6.98/10',
 '6.9921/10',
 '6/10',
 '6/11',
 '6/13',
 '6/20',
 '6/5',
 '6/6',
 '6/8',
 '60/100',
 '61/00',
 '61/100',
 '62/100',
 '63/100',
 '64/100',
 '65/100',
 '66/100',
 '66/70',
 '67',
 '67/10',
 '67/100',
 '68',
 '68/100',
 '69/100',
 '69/70',
 '7',
 '7.001/10',
 '7.00122/10',
 '7.01/10',
 '7.0155/10',
 '7.02/10',
 '7.021/10',
 '7.04/10',
 '7.05/10',
 '7.0921/10',
 '7.1/10',
 '7.10/10',
 '7.111113314/10',
 '7.12/10',
 '7.15/10',
 '7.18321/10',
 '7.2/10',
 '7.21/10',
 '7.212121/10',
 '7.218/10',
 '7.22/10',
 '7.2234238/10',
 '7.25/10',
 '7.2521/10',
 '7.2621/10',
 '7.3/10',
 '7.35/10',
 '7.3821/10',
 '7.3856/10',
 '7.4/10',
 '7.42/10',
 '7.44/10',
 '7.45/10',
 '7.48/10',
 '7.49/10',
 '7.4921/10',
 '7.5/10',
 '7.5/20',
 '7.5211/10',
 '7.5314585/10',
 '7.55/10',
 '7.57/10',
 '7.6/10',
 '7.61/10',
 '7.621/10',
 '7.62121/10',
 '7.65/10',
 '7.696/10',
 '7.7/10',
 '7.75/10',
 '7.79/10',
 '7.8/10',
 '7.825/10',
 '7.83/10',
 '7.85/10',
 '7.87/10',
 '7.89/10',
 '7.892/10',
 '7.9/10',
 '7.94/10',
 '7.94215/10',
 '7.95/10',
 '7.96/10',
 '7.98/10',
 '7/10',
 '7/11',
 '7/20',
 '7/5',
 '7/8',
 '70',
 '70/100',
 '71/100',
 '72',
 '72/100',
 '73/10',
 '73/100',
 '74/100',
 '75',
 '75/10',
 '75/100',
 '76/10',
 '76/100',
 '77',
 '77/100',
 '78/100',
 '79/100',
 '79/80',
 '8',
 '8.01/10',
 '8.05/10',
 '8.1/10',
 '8.10/10',
 '8.124/10',
 '8.15/10',
 '8.16/10',
 '8.19/10',
 '8.1921/10',
 '8.199/10',
 '8.2/10',
 '8.21/10',
 '8.212121/10',
 '8.225/10',
 '8.24/10',
 '8.25/10',
 '8.251/10',
 '8.2521/10',
 '8.26/10',
 '8.2621/10',
 '8.3/10',
 '8.3/100',
 '8.30/10',
 '8.32/10',
 '8.32321/10',
 '8.327/10',
 '8.35/10',
 '8.3721/10',
 '8.385/10',
 '8.39421/10',
 '8.4/10',
 '8.42/10',
 '8.425/10',
 '8.45/10',
 '8.453895/10',
 '8.458/10',
 '8.485/10',
 '8.496/10',
 '8.5/10',
 '8.5/5',
 '8.50/10',
 '8.53899/10',
 '8.55/10',
 '8.56/10',
 '8.57/10',
 '8.5788222/10',
 '8.6/10',
 '8.61/10',
 '8.621/10',
 '8.65/10',
 '8.666/10',
 '8.67/10',
 '8.68/10',
 '8.692121/10',
 '8.7/10',
 '8.70/10',
 '8.71/10',
 '8.72/10',
 '8.7328/10',
 '8.735/10',
 '8.74/10',
 '8.75/10',
 '8.76/10',
 '8.765/10',
 '8.8/10',
 '8.84/10',
 '8.85/10',
 '8.87/10',
 '8.88/10',
 '8.881/10',
 '8.89/10',
 '8.899327/10',
 '8.9/10',
 '8.901/10',
 '8.92/10',
 '8.921/10',
 '8.95/10',
 '8.9521/10',
 '8.9621/10',
 '8.98/10',
 '8.99/10',
 '8.999/10',
 '8/10',
 '8/100',
 '8/20',
 '8/5',
 '80',
 '80/100',
 '81/100',
 '82/100',
 '83/100',
 '84/100',
 '85/100',
 '86/100',
 '87/10',
 '87/100',
 '88',
 '88/100',
 '89',
 '89/100',
 '9',
 '9.01/10',
 '9.021/10',
 '9.1/10',
 '9.12/10',
 '9.121/10',
 '9.1221/10',
 '9.14/10',
 '9.1421/10',
 '9.145/10',
 '9.15/10',
 '9.16/10',
 '9.18/10',
 '9.188/10',
 '9.19/10',
 '9.2/10',
 '9.20/10',
 '9.2021/10',
 '9.21/10',
 '9.25/10',
 '9.26/10',
 '9.3/10',
 '9.30/10',
 '9.33/10',
 '9.35/10',
 '9.38/10',
 '9.4/10',
 '9.45/10',
 '9.46/10',
 '9.48/10',
 '9.49/10',
 '9.5/10',
 '9.5/20',
 '9.5/5',
 '9.50/20',
 '9.51/10',
 '9.52/10',
 '9.552/10',
 '9.56/10',
 '9.6/10',
 '9.6421/10',
 '9.649821/10',
 '9.65/10',
 '9.66/10',
 '9.67/10',
 '9.68/10',
 '9.7/10',
 '9.73889/10',
 '9.74/10',
 '9.75/10',
 '9.76/10',
 '9.78/10',
 '9.79/10',
 '9.8/10',
 '9.85/10',
 '9.851/10',
 '9.8521/10',
 '9.85621/10',
 '9.86/10',
 '9.865/10',
 '9.87/10',
 '9.88/10',
 '9.889/10',
 '9.89/10',
 '9.9/10',
 '9.921/10',
 '9.95/10',
 '9.99/10',
 '9/10',
 '9/100',
 '9/20',
 '9/5',
 '90',
 '90/100',
 '91/100',
 '910',
 '92/100',
 '920',
 '93/100',
 '94/100',
 '95',
 '95/100',
 '95/95',
 '96/100',
 '97/100',
 '98/100',
 '99/100',
 'A',
 'A-',
 'B',
 'B+',
 'B-',
 'C',
 'C+',
 'C-',
 'D',
 'D+',
 'D-',
 'F'}

### 2. Sample Testing

In [86]:
df = pd.DataFrame({'score': [ '95','96/100','3.5/5.7','7.5/5','90/95', '0/4', '5/0', 'A+', 'B-', 'C']})

In [87]:
import re
pattern1 = re.compile('[\d\.]*\/[\d\.]*') 
tt = df['score'].str.findall(pattern1).str.get(0)

In [88]:
tt

0        NaN
1     96/100
2    3.5/5.7
3      7.5/5
4      90/95
5        0/4
6        5/0
7        NaN
8        NaN
9        NaN
Name: score, dtype: object

In [89]:
for row in df['score'].index:
    print(row)

0
1
2
3
4
5
6
7
8
9

In [90]:
df

     score
0       95
1   96/100
2  3.5/5.7
3    7.5/5
4    90/95
5      0/4
6      5/0
7       A+
8       B-
9        C

In [91]:
df2 = df.copy()

In [92]:
pattern1 = re.compile('([\d\.]*)\/([\d\.]*)') # 숫자 데이터
pattern2 = re.compile('(\w)') # 카테고리 데이터
delete_list = []

for row in df2['score'].index:
    print(row, df2.loc[row, 'score'])
    num_value = pattern1.search(df2.loc[row, 'score'])
    cat_value = pattern2.search(df2.loc[row, 'score'])

    # 숫자/숫자 형태
    if(num_value):
        print('num')
        numerator = float(num_value.group(1))
        denominator = float(num_value.group(2))
        # 분모가 0인 경우
        if(denominator == 0):
            delete_list.append(row)
            print("삭제대상")
        else:
            print(numerator/denominator)
            df2.loc[row, 'score'] = numerator/denominator
    
    # 카테고리 형태
    elif(cat_value):
        print('cat')
        print(cat_value.group(0))
        df2.loc[row, 'score'] = cat_value.group(0)
    
    print()

0 95
cat
9

1 96/100
num
0.96

2 3.5/5.7
num
0.6140350877192983

3 7.5/5
num
1.5

4 90/95
num
0.9473684210526315

5 0/4
num
0.0

6 5/0
num
삭제대상

7 A+
cat
A

8 B-
cat
B

9 C
cat
C

In [93]:
delete_list

[6]

In [94]:
df2.drop(df2.index[delete_list], inplace=True)

In [95]:
df2

      score
0         9
1      0.96
2  0.614035
3       1.5
4  0.947368
5       0.0
7         A
8         B
9         C

- Categorical 값 변환

In [96]:
cat_score = {'A': 1, 'B': 0.7, 'C': 0.5, 'D': 0.3, 'F': 0}
df2.replace(cat_score, inplace=True)

In [97]:
df2

      score
0         9
1      0.96
2  0.614035
3       1.5
4  0.947368
5       0.0
7         1
8       0.7
9       0.5

### 3. Review score 적용
- 전처리 예상 시간: 3시간 소요

In [104]:
df = rotten_review.copy()

In [105]:
df.head()

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
3,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...
6,m/0814255,Nick Schager,False,Slant Magazine,Rotten,1/4,2010-02-10,Harry Potter knockoffs don't come more transpa...
7,m/0814255,Bill Goodykoontz,True,Arizona Republic,Fresh,3.5/5,2010-02-10,"Percy Jackson isn't a great movie, but it's a ..."
8,m/0814255,Jordan Hoffman,False,UGO,Fresh,B,2010-02-10,"Fun, brisk and imaginative"
9,m/0814255,Jim Schembri,True,The Age (Australia),Fresh,3/5,2010-02-10,"Crammed with dragons, set-destroying fights an..."

In [106]:
import time
start_time = time.time()

pattern1 = re.compile('([\d\.]*)\/([\d\.]*)') # 숫자 데이터
pattern2 = re.compile('(\w)') # 카테고리 데이터
delete_list = []

for row in df.index:
#     print(row, df.loc[row, 'review_score'])
    num_value = pattern1.search(df.loc[row, 'review_score'])
    cat_value = pattern2.search(df.loc[row, 'review_score'])

    # 숫자/숫자 형태
    if(num_value):
#         print('num')
        numerator = float(num_value.group(1))
        denominator = float(num_value.group(2))
        # 분모가 0인 경우
        if(denominator == 0):
            delete_list.append(row)
#             print("삭제대상")
        else:
#             print(numerator/denominator)
            df.loc[row, 'review_score'] = numerator/denominator
    
    # 카테고리 형태
    elif(cat_value):
#         print('cat')
#         print(cat_value.group(0))
        df.loc[row, 'review_score'] = cat_value.group(0)
    
#     print()

In [108]:
# 시간 표시 함수
def format_time(elapsed):
    # 반올림
    elapsed_rounded = int(round((elapsed)))
    # hh:mm:ss으로 형태 변경
    return str(datetime.timedelta(seconds=elapsed_rounded))

In [111]:
print("  Data Labeling took: {:}".format(format_time(time.time() - start_time)))

  Data Labeling took: 11:20:31

In [112]:
# 분모가 0인 경우
delete_list

[337828, 658547]

In [113]:
df.drop(index = delete_list, inplace=True)

In [114]:
cat_score = {'A': 1, 'B': 0.7, 'C': 0.5, 'D': 0.3, 'F': 0}
df.replace(cat_score, inplace=True)

In [115]:
set(df.review_score)

{0,
 '0',
 0.004,
 0.0125,
 0.018518518518518517,
 0.02,
 0.020999999999999998,
 0.026000000000000002,
 0.03,
 0.037037037037037035,
 0.04,
 0.05,
 0.06,
 0.0625,
 0.065,
 0.066,
 0.0664363,
 0.06666666666666667,
 0.07221,
 0.075,
 0.07765823,
 0.07954545454545454,
 0.08,
 0.08199999999999999,
 0.083,
 0.08499999999999999,
 0.09,
 0.09090909090909091,
 0.096,
 0.1,
 0.11000000000000001,
 0.1111111111111111,
 0.12,
 0.121,
 0.125,
 0.13,
 0.13999999999999999,
 0.14,
 0.15,
 0.15242228,
 0.16,
 0.1665,
 0.16666666666666666,
 0.175,
 0.18,
 0.182,
 0.185,
 0.188,
 0.19,
 0.19444444444444445,
 0.19528,
 0.2,
 0.21,
 0.21000000000000002,
 0.22,
 0.22000000000000003,
 0.220282652,
 0.2212521,
 0.2222222222222222,
 0.22823030000000002,
 0.22999999999999998,
 0.23,
 0.24,
 0.248,
 0.25,
 0.26,
 0.265,
 0.27,
 0.274,
 0.275,
 0.27999999999999997,
 0.28,
 0.2892521821,
 0.29,
 0.29500000000000004,
 0.3,
 0.3021,
 0.30782,
 0.31,
 0.3125,
 0.32,
 0.32121,
 0.3222423,
 0.324,
 0.325,
 0.32999999999999996,
 0.33,
 0.3333333333333333,
 0.33999999999999997,
 0.34,
 0.35,
 0.35150000000000003,
 0.355,
 0.356339,
 0.36,
 0.365,
 0.37,
 0.375,
 0.37521,
 0.376,
 0.37822391,
 0.38,
 0.383412437,
 0.385,
 0.39,
 0.399,
 0.4,
 0.40001,
 0.4021,
 0.40552400000000005,
 0.41,
 0.41436409999999996,
 0.4166666666666667,
 0.42,
 0.42000000000000004,
 0.421,
 0.42110000000000003,
 0.42112,
 0.421382343,
 0.422,
 0.42400000000000004,
 0.425,
 0.4293382,
 0.43,
 0.43333333333333335,
 0.43499999999999994,
 0.4364221,
 0.4375,
 0.44,
 0.44000000000000006,
 0.442,
 0.445,
 0.45,
 0.45099999999999996,
 0.4521,
 0.45454545454545453,
 0.45499999999999996,
 0.4558,
 0.45599999999999996,
 0.45999999999999996,
 0.46,
 0.46153846153846156,
 0.465,
 0.47,
 0.47000000000000003,
 0.475,
 0.479,
 0.48,
 0.4827,
 0.485,
 0.48600000000000004,
 0.489,
 0.489215,
 0.49,
 0.49000000000000005,
 0.495,
 0.49834326000000007,
 0.49837,
 0.5,
 0.501,
 0.502120621,
 0.5046,
 0.505,
 0.51,
 0.512,
 0.5122099999999999,
 0.515,
 0.51921,
 0.52,
 0.521,
 0.5212,
 0.522,
 0.523,
 0.5232121000000001,
 0.525,
 0.5284849,
 0.53,
 0.5349999999999999,
 0.54,
 0.5422100000000001,
 0.544,
 0.545,
 0.5454545454545454,
 0.548,
 0.549,
 0.55,
 0.5509999999999999,
 0.5549999999999999,
 0.55542,
 0.5555555555555555,
 0.5559999999999999,
 0.557,
 0.5599999999999999,
 0.56,
 0.561,
 0.5623433899,
 0.5625,
 0.5650000000000001,
 0.56521,
 0.5660000000000001,
 0.56642,
 0.567,
 0.57,
 0.5700000000000001,
 0.572,
 0.575,
 0.5751000000000001,
 0.576,
 0.5780000000000001,
 0.58,
 0.581,
 0.5820000000000001,
 0.58311,
 0.5833333333333334,
 0.585,
 0.5871999999999999,
 0.588,
 0.58921,
 0.58943,
 0.5894999999999999,
 0.589521,
 0.59,
 0.5900000000000001,
 0.595,
 0.59737991,
 0.59821,
 0.59999,
 0.6,
 0.60000001,
 0.6000003231,
 0.600001,
 0.6000099999999999,
 0.600024,
 0.6001000000000001,
 0.601,
 0.602,
 0.602121,
 0.605,
 0.609,
 0.61,
 0.61121,
 0.615,
 0.616,
 0.619,
 0.62,
 0.624,
 0.625,
 0.626,
 0.63,
 0.635,
 0.6363636363636364,
 0.6375,
 0.64,
 0.645,
 0.64821,
 0.65,
 0.655,
 0.6599999999999999,
 0.66,
 0.665,
 0.6666666666666666,
 0.6679999999999999,
 0.67,
 0.675,
 0.6765,
 0.678,
 0.6799999999999999,
 0.68,
 0.6839999999999999,
 0.6849999999999999,
 0.68666,
 0.6875,
 0.68843,
 0.689,
 0.69,
 0.6900000000000001,
 0.6950000000000001,
 0.696,
 0.69621,
 0.697,
 0.6980000000000001,
 0.69921,
 0.7,
 0.7001000000000001,
 0.700122,
 0.701,
 0.70155,
 0.702,
 0.7021,
 0.704,
 0.705,
 0.708,
 0.70921,
 0.71,
 0.7111113313999999,
 0.712,
 0.7150000000000001,
 0.718321,
 0.72,
 0.721,
 0.7212121,
 0.7218,
 0.722,
 0.72234238,
 0.725,
 0.72521,
 0.72621,
 0.7272727272727273,
 0.73,
 0.735,
 0.73821,
 0.73856,
 0.74,
 0.742,
 0.744,
 0.745,
 0.748,
 0.749,
 0.7492099999999999,
 0.75,
 0.752,
 0.75211,
 0.75314585,
 0.755,
 0.757,
 0.76,
 0.761,
 0.7621,
 0.7621209999999999,
 0.765,
 0.7696,
 0.77,
 0.775,
 0.779,
 0.78,
 0.7825,
 0.783,
 0.7849999999999999,
 0.787,
 0.7889999999999999,
 0.7892,
 0.79,
 0.794,
 0.794215,
 0.795,
 0.796,
 0.798,
 0.8,
 0.8009999999999999,
 0.805,
 0.8099999999999999,
 0.81,
 0.8124,
 0.8125,
 0.8150000000000001,
 0.8160000000000001,
 0.819,
 0.81921,
 0.8199,
 0.82,
 0.8210000000000001,
 0.8212121,
 0.8225,
 0.8240000000000001,
 0.825,
 0.8251,
 0.82521,
 0.826,
 0.82621,
 0.83,
 0.8300000000000001,
 0.8320000000000001,
 0.832321,
 0.8327,
 0.8333333333333334,
 0.835,
 0.83721,
 0.8375,
 0.8385,
 0.839421,
 0.84,
 0.8400000000000001,
 0.842,
 0.8425,
 0.845,
 0.8453894999999999,
 0.8458,
 0.8484999999999999,
 0.8496,
 0.85,
 0.853899,
 0.8550000000000001,
 0.8560000000000001,
 0.857,
 0.8578822199999999,
 0.86,
 0.861,
 0.8621000000000001,
 0.865,
 0.8666,
 0.867,
 0.868,
 0.8692121,
 0.8699999999999999,
 0.87,
 0.8710000000000001,
 0.8720000000000001,
 0.87328,
 0.8734999999999999,
 0.874,
 0.875,
 0.876,
 0.8765000000000001,
 0.88,
 0.8800000000000001,
 0.884,
 0.885,
 0.8869999999999999,
 0.8880000000000001,
 0.8881,
 0.889,
 0.8899326999999999,
 0.89,
 0.8901,
 0.892,
 0.8920999999999999,
 0.8949999999999999,
 0.89521,
 0.89621,
 0.898,
 0.899,
 0.8999,
 0.9,
 0.901,
 0.9021000000000001,
 0.9099999999999999,
 0.91,
 0.9119999999999999,
 0.9121,
 0.91221,
 0.914,
 0.91421,
 0.9145,
 0.915,
 0.916,
 0.9166666666666666,
 0.9179999999999999,
 0.9188000000000001,
 0.9189999999999999,
 0.9199999999999999,
 0.92,
 0.92021,
 0.921,
 0.925,
 0.9259999999999999,
 0.93,
 0.933,
 0.9349999999999999,
 0.9375,
 0.9380000000000001,
 0.94,
 0.9400000000000001,
 0.9428571428571428,
 0.945,
 0.9460000000000001,
 0.9480000000000001,
 0.9490000000000001,
 0.95,
 0.951,
 0.952,
 0.9551999999999999,
 0.9560000000000001,
 0.96,
 0.9642099999999999,
 0.9649821,
 0.9650000000000001,
 0.966,
 0.967,
 0.968,
 0.97,
 0.973889,
 0.974,
 0.975,
 0.976,
 0.978,
 0.9789999999999999,
 0.98,
 0.9800000000000001,
 0.9833333333333333,
 0.985,
 0.9851000000000001,
 0.98521,
 0.9856210000000001,
 0.9857142857142858,
 0.986,
 0.9865,
 0.9869999999999999,
 0.9875,
 0.9880000000000001,
 0.9888999999999999,
 0.9890000000000001,
 0.99,
 0.9921,
 0.9949999999999999,
 0.999,
 '1',
 1.0,
 1.05,
 1.1,
 1.125,
 1.1428571428571428,
 1.1666666666666667,
 1.2,
 1.4,
 1.6,
 1.7,
 1.8,
 1.9,
 '2',
 '3',
 '4',
 '5',
 '6',
 6.25,
 6.7,
 '7',
 7.3,
 7.5,
 7.6,
 '8',
 8.7,
 8.75,
 '9',
 9.0}

In [116]:
path

'./../../data/rotten_tomato/'

In [119]:
# 1차 저장
df.to_csv(path+'rotten_review_scaled_new.csv', index=True)

In [120]:
df.head()

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
3,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,0.7,2010-02-09,Whether audiences will get behind The Lightnin...
6,m/0814255,Nick Schager,False,Slant Magazine,Rotten,0.25,2010-02-10,Harry Potter knockoffs don't come more transpa...
7,m/0814255,Bill Goodykoontz,True,Arizona Republic,Fresh,0.7,2010-02-10,"Percy Jackson isn't a great movie, but it's a ..."
8,m/0814255,Jordan Hoffman,False,UGO,Fresh,0.7,2010-02-10,"Fun, brisk and imaginative"
9,m/0814255,Jim Schembri,True,The Age (Australia),Fresh,0.6,2010-02-10,"Crammed with dragons, set-destroying fights an..."

### 4. 긍정/부정 레이블 표시

In [122]:
df = pd.read_csv(path+'rotten_review_scaled_new.csv')

In [123]:
len(df)

752732

In [125]:
df.drop('Unnamed: 0', axis=1,inplace=True)

In [126]:
df.head()

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,0.70,2010-02-09,Whether audiences will get behind The Lightnin...
1,m/0814255,Nick Schager,False,Slant Magazine,Rotten,0.25,2010-02-10,Harry Potter knockoffs don't come more transpa...
2,m/0814255,Bill Goodykoontz,True,Arizona Republic,Fresh,0.70,2010-02-10,"Percy Jackson isn't a great movie, but it's a ..."
3,m/0814255,Jordan Hoffman,False,UGO,Fresh,0.70,2010-02-10,"Fun, brisk and imaginative"
4,m/0814255,Jim Schembri,True,The Age (Australia),Fresh,0.60,2010-02-10,"Crammed with dragons, set-destroying fights an..."

In [127]:
# 숫자형태가 아닌 경우 조회 : 단, '11'도 숫자로 인식
df[pd.to_numeric(df.review_score, errors='coerce').isnull()]

Empty DataFrame
Columns: [rotten_tomatoes_link, critic_name, top_critic, publisher_name, review_type, review_score, review_date, review_content]
Index: []

In [128]:
df['review_score'] = pd.to_numeric(df.review_score)

In [129]:
set(df.review_score)

{0.0,
 0.004,
 0.0125,
 0.0185185185185185,
 0.02,
 0.0209999999999999,
 0.026,
 0.03,
 0.037037037037037,
 0.04,
 0.05,
 0.06,
 0.0625,
 0.065,
 0.066,
 0.0664363,
 0.0666666666666666,
 0.07221,
 0.075,
 0.07765823,
 0.0795454545454545,
 0.08,
 0.0819999999999999,
 0.083,
 0.0849999999999999,
 0.09,
 0.0909090909090909,
 0.096,
 0.1,
 0.11,
 0.1111111111111111,
 0.12,
 0.121,
 0.125,
 0.13,
 0.1399999999999999,
 0.14,
 0.15,
 0.15242228,
 0.16,
 0.1665,
 0.1666666666666666,
 0.175,
 0.18,
 0.182,
 0.185,
 0.188,
 0.19,
 0.1944444444444444,
 0.19528,
 0.2,
 0.21,
 0.22,
 0.220282652,
 0.2212521,
 0.2222222222222222,
 0.2282303,
 0.2299999999999999,
 0.23,
 0.24,
 0.248,
 0.25,
 0.26,
 0.265,
 0.27,
 0.274,
 0.275,
 0.2799999999999999,
 0.28,
 0.2892521821,
 0.29,
 0.295,
 0.3,
 0.3021,
 0.30782,
 0.31,
 0.3125,
 0.32,
 0.32121,
 0.3222423,
 0.324,
 0.325,
 0.3299999999999999,
 0.33,
 0.3333333333333333,
 0.3399999999999999,
 0.34,
 0.35,
 0.3515,
 0.355,
 0.356339,
 0.36,
 0.365,
 0.37,
 0.375,
 0.37521,
 0.376,
 0.37822391,
 0.38,
 0.383412437,
 0.385,
 0.39,
 0.399,
 0.4,
 0.40001,
 0.4021,
 0.405524,
 0.41,
 0.4143640999999999,
 0.4166666666666667,
 0.42,
 0.421,
 0.4211,
 0.42112,
 0.421382343,
 0.422,
 0.424,
 0.425,
 0.4293382,
 0.43,
 0.4333333333333333,
 0.4349999999999999,
 0.4364221,
 0.4375,
 0.44,
 0.442,
 0.445,
 0.45,
 0.4509999999999999,
 0.4521,
 0.4545454545454545,
 0.4549999999999999,
 0.4558,
 0.4559999999999999,
 0.4599999999999999,
 0.46,
 0.4615384615384615,
 0.465,
 0.47,
 0.475,
 0.479,
 0.48,
 0.4827,
 0.485,
 0.486,
 0.489,
 0.489215,
 0.49,
 0.495,
 0.49834326,
 0.49837,
 0.5,
 0.501,
 0.502120621,
 0.5046,
 0.505,
 0.51,
 0.512,
 0.5122099999999999,
 0.515,
 0.51921,
 0.52,
 0.521,
 0.5212,
 0.522,
 0.523,
 0.5232121000000001,
 0.525,
 0.5284849,
 0.53,
 0.5349999999999999,
 0.54,
 0.5422100000000001,
 0.544,
 0.545,
 0.5454545454545454,
 0.548,
 0.549,
 0.55,
 0.5509999999999999,
 0.5549999999999999,
 0.55542,
 0.5555555555555555,
 0.5559999999999999,
 0.557,
 0.5599999999999999,
 0.56,
 0.561,
 0.5623433899,
 0.5625,
 0.5650000000000001,
 0.56521,
 0.5660000000000001,
 0.56642,
 0.567,
 0.57,
 0.5700000000000001,
 0.572,
 0.575,
 0.5751000000000001,
 0.576,
 0.5780000000000001,
 0.58,
 0.581,
 0.5820000000000001,
 0.58311,
 0.5833333333333334,
 0.585,
 0.5871999999999999,
 0.588,
 0.58921,
 0.58943,
 0.5894999999999999,
 0.589521,
 0.59,
 0.5900000000000001,
 0.595,
 0.59737991,
 0.59821,
 0.59999,
 0.6,
 0.60000001,
 0.6000003231,
 0.600001,
 0.6000099999999999,
 0.600024,
 0.6001000000000001,
 0.601,
 0.602,
 0.602121,
 0.605,
 0.609,
 0.61,
 0.61121,
 0.615,
 0.616,
 0.619,
 0.62,
 0.624,
 0.625,
 0.626,
 0.63,
 0.635,
 0.6363636363636364,
 0.6375,
 0.64,
 0.645,
 0.64821,
 0.65,
 0.655,
 0.6599999999999999,
 0.66,
 0.665,
 0.6666666666666666,
 0.6679999999999999,
 0.67,
 0.675,
 0.6765,
 0.678,
 0.6799999999999999,
 0.68,
 0.6839999999999999,
 0.6849999999999999,
 0.68666,
 0.6875,
 0.68843,
 0.689,
 0.69,
 0.6900000000000001,
 0.6950000000000001,
 0.696,
 0.69621,
 0.697,
 0.6980000000000001,
 0.69921,
 0.7,
 0.7001000000000001,
 0.700122,
 0.701,
 0.70155,
 0.702,
 0.7021,
 0.704,
 0.705,
 0.708,
 0.70921,
 0.71,
 0.7111113313999999,
 0.712,
 0.7150000000000001,
 0.718321,
 0.72,
 0.721,
 0.7212121,
 0.7218,
 0.722,
 0.72234238,
 0.725,
 0.72521,
 0.72621,
 0.7272727272727273,
 0.73,
 0.735,
 0.73821,
 0.73856,
 0.74,
 0.742,
 0.744,
 0.745,
 0.748,
 0.749,
 0.7492099999999999,
 0.75,
 0.752,
 0.75211,
 0.75314585,
 0.755,
 0.757,
 0.76,
 0.761,
 0.7621,
 0.7621209999999999,
 0.765,
 0.7696,
 0.77,
 0.775,
 0.779,
 0.78,
 0.7825,
 0.783,
 0.7849999999999999,
 0.787,
 0.7889999999999999,
 0.7892,
 0.79,
 0.794,
 0.794215,
 0.795,
 0.796,
 0.798,
 0.8,
 0.8009999999999999,
 0.805,
 0.8099999999999999,
 0.81,
 0.8124,
 0.8125,
 0.8150000000000001,
 0.8160000000000001,
 0.819,
 0.81921,
 0.8199,
 0.82,
 0.8210000000000001,
 0.8212121,
 0.8225,
 0.8240000000000001,
 0.825,
 0.8251,
 0.82521,
 0.826,
 0.82621,
 0.83,
 0.8300000000000001,
 0.8320000000000001,
 0.832321,
 0.8327,
 0.8333333333333334,
 0.835,
 0.83721,
 0.8375,
 0.8385,
 0.839421,
 0.84,
 0.8400000000000001,
 0.842,
 0.8425,
 0.845,
 0.8453894999999999,
 0.8458,
 0.8484999999999999,
 0.8496,
 0.85,
 0.853899,
 0.8550000000000001,
 0.8560000000000001,
 0.857,
 0.8578822199999999,
 0.86,
 0.861,
 0.8621000000000001,
 0.865,
 0.8666,
 0.867,
 0.868,
 0.8692121,
 0.8699999999999999,
 0.87,
 0.8710000000000001,
 0.8720000000000001,
 0.87328,
 0.8734999999999999,
 0.874,
 0.875,
 0.876,
 0.8765000000000001,
 0.88,
 0.8800000000000001,
 0.884,
 0.885,
 0.8869999999999999,
 0.8880000000000001,
 0.8881,
 0.889,
 0.8899326999999999,
 0.89,
 0.8901,
 0.892,
 0.8920999999999999,
 0.8949999999999999,
 0.89521,
 0.89621,
 0.898,
 0.899,
 0.8999,
 0.9,
 0.901,
 0.9021,
 0.91,
 0.912,
 0.9121,
 0.91221,
 0.914,
 0.91421,
 0.9145,
 0.915,
 0.916,
 0.9166666666666666,
 0.918,
 0.9188,
 0.919,
 0.92,
 0.92021,
 0.921,
 0.925,
 0.926,
 0.93,
 0.933,
 0.935,
 0.9375,
 0.938,
 0.94,
 0.9428571428571428,
 0.945,
 0.946,
 0.948,
 0.949,
 0.95,
 0.951,
 0.952,
 0.9552,
 0.956,
 0.96,
 0.96421,
 0.9649821,
 0.965,
 0.966,
 0.967,
 0.968,
 0.97,
 0.973889,
 0.974,
 0.975,
 0.976,
 0.978,
 0.979,
 0.98,
 0.9833333333333332,
 0.985,
 0.9851,
 0.98521,
 0.985621,
 0.9857142857142858,
 0.986,
 0.9865,
 0.987,
 0.9875,
 0.988,
 0.9889,
 0.989,
 0.99,
 0.9921,
 0.995,
 0.999,
 1.0,
 1.05,
 1.1,
 1.125,
 1.1428571428571428,
 1.1666666666666667,
 1.2,
 1.4,
 1.6,
 1.7,
 1.8,
 1.9,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 6.25,
 6.7,
 7.0,
 7.3,
 7.5,
 7.6,
 8.0,
 8.7,
 8.75,
 9.0}

In [130]:
len(df)

752732

In [131]:
sum(df['review_score'].notnull())

752732

### 4. 1보다 크지 않은 수만 필터링

In [132]:
# 1보다 큰 평점 수
sum(df['review_score'] > 1.0)

1535

In [133]:
sum(df['review_score'] <= 1.0)

751197

In [134]:
clean_df = df[df['review_score'] <= 1.0]

In [135]:
set(clean_df.review_score)

{0.0,
 0.004,
 0.0125,
 0.0185185185185185,
 0.02,
 0.0209999999999999,
 0.026,
 0.03,
 0.037037037037037,
 0.04,
 0.05,
 0.06,
 0.0625,
 0.065,
 0.066,
 0.0664363,
 0.0666666666666666,
 0.07221,
 0.075,
 0.07765823,
 0.0795454545454545,
 0.08,
 0.0819999999999999,
 0.083,
 0.0849999999999999,
 0.09,
 0.0909090909090909,
 0.096,
 0.1,
 0.11,
 0.1111111111111111,
 0.12,
 0.121,
 0.125,
 0.13,
 0.1399999999999999,
 0.14,
 0.15,
 0.15242228,
 0.16,
 0.1665,
 0.1666666666666666,
 0.175,
 0.18,
 0.182,
 0.185,
 0.188,
 0.19,
 0.1944444444444444,
 0.19528,
 0.2,
 0.21,
 0.22,
 0.220282652,
 0.2212521,
 0.2222222222222222,
 0.2282303,
 0.2299999999999999,
 0.23,
 0.24,
 0.248,
 0.25,
 0.26,
 0.265,
 0.27,
 0.274,
 0.275,
 0.2799999999999999,
 0.28,
 0.2892521821,
 0.29,
 0.295,
 0.3,
 0.3021,
 0.30782,
 0.31,
 0.3125,
 0.32,
 0.32121,
 0.3222423,
 0.324,
 0.325,
 0.3299999999999999,
 0.33,
 0.3333333333333333,
 0.3399999999999999,
 0.34,
 0.35,
 0.3515,
 0.355,
 0.356339,
 0.36,
 0.365,
 0.37,
 0.375,
 0.37521,
 0.376,
 0.37822391,
 0.38,
 0.383412437,
 0.385,
 0.39,
 0.399,
 0.4,
 0.40001,
 0.4021,
 0.405524,
 0.41,
 0.4143640999999999,
 0.4166666666666667,
 0.42,
 0.421,
 0.4211,
 0.42112,
 0.421382343,
 0.422,
 0.424,
 0.425,
 0.4293382,
 0.43,
 0.4333333333333333,
 0.4349999999999999,
 0.4364221,
 0.4375,
 0.44,
 0.442,
 0.445,
 0.45,
 0.4509999999999999,
 0.4521,
 0.4545454545454545,
 0.4549999999999999,
 0.4558,
 0.4559999999999999,
 0.4599999999999999,
 0.46,
 0.4615384615384615,
 0.465,
 0.47,
 0.475,
 0.479,
 0.48,
 0.4827,
 0.485,
 0.486,
 0.489,
 0.489215,
 0.49,
 0.495,
 0.49834326,
 0.49837,
 0.5,
 0.501,
 0.502120621,
 0.5046,
 0.505,
 0.51,
 0.512,
 0.5122099999999999,
 0.515,
 0.51921,
 0.52,
 0.521,
 0.5212,
 0.522,
 0.523,
 0.5232121000000001,
 0.525,
 0.5284849,
 0.53,
 0.5349999999999999,
 0.54,
 0.5422100000000001,
 0.544,
 0.545,
 0.5454545454545454,
 0.548,
 0.549,
 0.55,
 0.5509999999999999,
 0.5549999999999999,
 0.55542,
 0.5555555555555555,
 0.5559999999999999,
 0.557,
 0.5599999999999999,
 0.56,
 0.561,
 0.5623433899,
 0.5625,
 0.5650000000000001,
 0.56521,
 0.5660000000000001,
 0.56642,
 0.567,
 0.57,
 0.5700000000000001,
 0.572,
 0.575,
 0.5751000000000001,
 0.576,
 0.5780000000000001,
 0.58,
 0.581,
 0.5820000000000001,
 0.58311,
 0.5833333333333334,
 0.585,
 0.5871999999999999,
 0.588,
 0.58921,
 0.58943,
 0.5894999999999999,
 0.589521,
 0.59,
 0.5900000000000001,
 0.595,
 0.59737991,
 0.59821,
 0.59999,
 0.6,
 0.60000001,
 0.6000003231,
 0.600001,
 0.6000099999999999,
 0.600024,
 0.6001000000000001,
 0.601,
 0.602,
 0.602121,
 0.605,
 0.609,
 0.61,
 0.61121,
 0.615,
 0.616,
 0.619,
 0.62,
 0.624,
 0.625,
 0.626,
 0.63,
 0.635,
 0.6363636363636364,
 0.6375,
 0.64,
 0.645,
 0.64821,
 0.65,
 0.655,
 0.6599999999999999,
 0.66,
 0.665,
 0.6666666666666666,
 0.6679999999999999,
 0.67,
 0.675,
 0.6765,
 0.678,
 0.6799999999999999,
 0.68,
 0.6839999999999999,
 0.6849999999999999,
 0.68666,
 0.6875,
 0.68843,
 0.689,
 0.69,
 0.6900000000000001,
 0.6950000000000001,
 0.696,
 0.69621,
 0.697,
 0.6980000000000001,
 0.69921,
 0.7,
 0.7001000000000001,
 0.700122,
 0.701,
 0.70155,
 0.702,
 0.7021,
 0.704,
 0.705,
 0.708,
 0.70921,
 0.71,
 0.7111113313999999,
 0.712,
 0.7150000000000001,
 0.718321,
 0.72,
 0.721,
 0.7212121,
 0.7218,
 0.722,
 0.72234238,
 0.725,
 0.72521,
 0.72621,
 0.7272727272727273,
 0.73,
 0.735,
 0.73821,
 0.73856,
 0.74,
 0.742,
 0.744,
 0.745,
 0.748,
 0.749,
 0.7492099999999999,
 0.75,
 0.752,
 0.75211,
 0.75314585,
 0.755,
 0.757,
 0.76,
 0.761,
 0.7621,
 0.7621209999999999,
 0.765,
 0.7696,
 0.77,
 0.775,
 0.779,
 0.78,
 0.7825,
 0.783,
 0.7849999999999999,
 0.787,
 0.7889999999999999,
 0.7892,
 0.79,
 0.794,
 0.794215,
 0.795,
 0.796,
 0.798,
 0.8,
 0.8009999999999999,
 0.805,
 0.8099999999999999,
 0.81,
 0.8124,
 0.8125,
 0.8150000000000001,
 0.8160000000000001,
 0.819,
 0.81921,
 0.8199,
 0.82,
 0.8210000000000001,
 0.8212121,
 0.8225,
 0.8240000000000001,
 0.825,
 0.8251,
 0.82521,
 0.826,
 0.82621,
 0.83,
 0.8300000000000001,
 0.8320000000000001,
 0.832321,
 0.8327,
 0.8333333333333334,
 0.835,
 0.83721,
 0.8375,
 0.8385,
 0.839421,
 0.84,
 0.8400000000000001,
 0.842,
 0.8425,
 0.845,
 0.8453894999999999,
 0.8458,
 0.8484999999999999,
 0.8496,
 0.85,
 0.853899,
 0.8550000000000001,
 0.8560000000000001,
 0.857,
 0.8578822199999999,
 0.86,
 0.861,
 0.8621000000000001,
 0.865,
 0.8666,
 0.867,
 0.868,
 0.8692121,
 0.8699999999999999,
 0.87,
 0.8710000000000001,
 0.8720000000000001,
 0.87328,
 0.8734999999999999,
 0.874,
 0.875,
 0.876,
 0.8765000000000001,
 0.88,
 0.8800000000000001,
 0.884,
 0.885,
 0.8869999999999999,
 0.8880000000000001,
 0.8881,
 0.889,
 0.8899326999999999,
 0.89,
 0.8901,
 0.892,
 0.8920999999999999,
 0.8949999999999999,
 0.89521,
 0.89621,
 0.898,
 0.899,
 0.8999,
 0.9,
 0.901,
 0.9021,
 0.91,
 0.912,
 0.9121,
 0.91221,
 0.914,
 0.91421,
 0.9145,
 0.915,
 0.916,
 0.9166666666666666,
 0.918,
 0.9188,
 0.919,
 0.92,
 0.92021,
 0.921,
 0.925,
 0.926,
 0.93,
 0.933,
 0.935,
 0.9375,
 0.938,
 0.94,
 0.9428571428571428,
 0.945,
 0.946,
 0.948,
 0.949,
 0.95,
 0.951,
 0.952,
 0.9552,
 0.956,
 0.96,
 0.96421,
 0.9649821,
 0.965,
 0.966,
 0.967,
 0.968,
 0.97,
 0.973889,
 0.974,
 0.975,
 0.976,
 0.978,
 0.979,
 0.98,
 0.9833333333333332,
 0.985,
 0.9851,
 0.98521,
 0.985621,
 0.9857142857142858,
 0.986,
 0.9865,
 0.987,
 0.9875,
 0.988,
 0.9889,
 0.989,
 0.99,
 0.9921,
 0.995,
 0.999,
 1.0}

In [137]:
clean_df.to_csv(path+'rotten_review_scaled_clean.csv', index=True)

### 5. Label 설정

In [138]:
clean_df = pd.read_csv(path+'rotten_review_scaled_clean.csv')
clean_df.drop('Unnamed: 0', axis=1,inplace=True)

In [139]:
clean_df.head()

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,0.70,2010-02-09,Whether audiences will get behind The Lightnin...
1,m/0814255,Nick Schager,False,Slant Magazine,Rotten,0.25,2010-02-10,Harry Potter knockoffs don't come more transpa...
2,m/0814255,Bill Goodykoontz,True,Arizona Republic,Fresh,0.70,2010-02-10,"Percy Jackson isn't a great movie, but it's a ..."
3,m/0814255,Jordan Hoffman,False,UGO,Fresh,0.70,2010-02-10,"Fun, brisk and imaginative"
4,m/0814255,Jim Schembri,True,The Age (Australia),Fresh,0.60,2010-02-10,"Crammed with dragons, set-destroying fights an..."

- review_score >= 0.7 : 1
- review_score <= 0.3 : 0

In [140]:
pos_condition = clean_df.review_score >= 0.7
neg_condition = clean_df.review_score <= 0.3

In [141]:
pos_list = clean_df[pos_condition].index
neg_list = clean_df[neg_condition].index

In [142]:
clean_df.loc[pos_list, 'label'] = 1
clean_df.loc[neg_list, 'label'] = 0

In [143]:
clean_df

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content,label
0,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,0.70,2010-02-09,Whether audiences will get behind The Lightnin...,1.0
1,m/0814255,Nick Schager,False,Slant Magazine,Rotten,0.25,2010-02-10,Harry Potter knockoffs don't come more transpa...,0.0
2,m/0814255,Bill Goodykoontz,True,Arizona Republic,Fresh,0.70,2010-02-10,"Percy Jackson isn't a great movie, but it's a ...",1.0
3,m/0814255,Jordan Hoffman,False,UGO,Fresh,0.70,2010-02-10,"Fun, brisk and imaginative",1.0
4,m/0814255,Jim Schembri,True,The Age (Australia),Fresh,0.60,2010-02-10,"Crammed with dragons, set-destroying fights an...",NaN
...,...,...,...,...,...,...,...,...,...
751192,m/zulu,Tony Sloman,False,Radio Times,Fresh,1.00,2017-07-10,The movie is a revelation.,1.0
751193,m/zulu_dawn,Ken Hanke,False,"Mountain Xpress (Asheville, NC)",Fresh,0.70,2007-03-07,"Seen today, it's not only a startling indictme...",1.0
751194,m/zulu_dawn,Dennis Schwartz,False,Dennis Schwartz Movie Reviews,Fresh,0.70,2010-09-16,A rousing visual spectacle that's a prequel of...,1.0
751195,m/zulu_dawn,Christopher Lloyd,False,Sarasota Herald-Tribune,Rotten,0.70,2011-02-28,"A simple two-act story: Prelude to war, and th...",1.0
751196,m/zulu_dawn,Brent McKnight,False,The Last Thing I See,Rotten,0.50,2020-07-09,Rides the line between being a pure artifact o...,NaN

In [144]:
clean_df.dropna(axis=0, inplace=True)

In [146]:
clean_df

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content,label
0,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,0.70,2010-02-09,Whether audiences will get behind The Lightnin...,1.0
1,m/0814255,Nick Schager,False,Slant Magazine,Rotten,0.25,2010-02-10,Harry Potter knockoffs don't come more transpa...,0.0
2,m/0814255,Bill Goodykoontz,True,Arizona Republic,Fresh,0.70,2010-02-10,"Percy Jackson isn't a great movie, but it's a ...",1.0
3,m/0814255,Jordan Hoffman,False,UGO,Fresh,0.70,2010-02-10,"Fun, brisk and imaginative",1.0
5,m/0814255,Mark Adams,False,Daily Mirror (UK),Fresh,0.80,2010-02-10,"This action-packed fantasy adventure, based on...",1.0
...,...,...,...,...,...,...,...,...,...
751191,m/zulu,Alex von Tunzelmann,True,Guardian,Fresh,0.70,2017-07-10,A brilliantly made dramatisation of Rorke's Dr...,1.0
751192,m/zulu,Tony Sloman,False,Radio Times,Fresh,1.00,2017-07-10,The movie is a revelation.,1.0
751193,m/zulu_dawn,Ken Hanke,False,"Mountain Xpress (Asheville, NC)",Fresh,0.70,2007-03-07,"Seen today, it's not only a startling indictme...",1.0
751194,m/zulu_dawn,Dennis Schwartz,False,Dennis Schwartz Movie Reviews,Fresh,0.70,2010-09-16,A rousing visual spectacle that's a prequel of...,1.0
751195,m/zulu_dawn,Christopher Lloyd,False,Sarasota Herald-Tribune,Rotten,0.70,2011-02-28,"A simple two-act story: Prelude to war, and th...",1.0

In [147]:
clean_df.label = clean_df.label.astype(int)

In [148]:
clean_df.head()

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content,label
0,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,0.70,2010-02-09,Whether audiences will get behind The Lightnin...,1
1,m/0814255,Nick Schager,False,Slant Magazine,Rotten,0.25,2010-02-10,Harry Potter knockoffs don't come more transpa...,0
2,m/0814255,Bill Goodykoontz,True,Arizona Republic,Fresh,0.70,2010-02-10,"Percy Jackson isn't a great movie, but it's a ...",1
3,m/0814255,Jordan Hoffman,False,UGO,Fresh,0.70,2010-02-10,"Fun, brisk and imaginative",1
5,m/0814255,Mark Adams,False,Daily Mirror (UK),Fresh,0.80,2010-02-10,"This action-packed fantasy adventure, based on...",1

In [153]:
total_len = len(clean_df)

In [149]:
print(f"Positive label 개수 : {sum(clean_df['label'] == 1.0)}")
print(f"Negative label 개수 : {sum(clean_df['label'] == 0.0)}")

Positive label 개수 : 372404
Negative label 개수 : 64773

In [154]:
print(f"Positive label 비율 : {sum(clean_df['label'] == 1.0)/total_len}")
print(f"Negative label 비율 : {sum(clean_df['label'] == 0.0)/total_len}")

Positive label 비율 : 0.8518380427149644
Negative label 비율 : 0.1481619572850356

In [155]:
clean_df.to_csv(path+'rotten_review_scaled_label.csv', index=False)